name: Build & Test

on:
  [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt update && sudo apt install cmake g++ clang-tidy -y

      - name: Configure
        run: cmake -B build -S .

      - name: Build
        run: cmake --build build

      - name: Run Tests
        run: cd build && ctest
